# SITE CONFIGURATION
baseurl: ""
url: "https://ivbravo.github.io"

# THEME-SPECIFIC CONFIGURATION
title: Galería de Arte | Art Gallery                    # site's title
description: "Ivan Bravo art gallery"                   # used by search engines
avatar: assets/img/author2.jpeg                         # Empty for no avatar in navbar
favicon: assets/favicon.ico                             # Icon displayed in the tab

# Header and footer text
header_text: welcome                                    # Change Blog header text
header_feature_image: assets/img/header.jpeg
header_feature_image_responsive: false
footer_text: ivanbravo2644@gmail.com | Copyright 2022

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true

# Features
# More in the _data folder for share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: false                                             # Enable if using math markup
mermaid: false                                           # Enable mermaid-js for sequence and diagrams
google_analytics: G-29HPLBP4QY                           # Tracking ID, e.g. "UA-000000-01"
cookie_consent: true                                     # To respect the usage of cookies
color_theme: auto                                        # auto, dark or light

# Comments
comments:
  disqus_shortname:                                     # Your discus shortname for comments
  cusdis_app_id:                                        # Your cusdis data-app-id
  utterances:                                           # Enable by filling below information. For more info, go to https://utteranc.es
    repo:                                               # your public comments repository (e.g. owner/repo)
    issue-term:                                         # Issue term (e.g. "comment" consider issues with this word in the title as comments)

# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"

# BUILD SETTINGS
sass:
  style: compressed
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed, jekyll-multiple-languages-plugin]
exclude: [".jekyll-cache", ".jekyll-metadata", ".idea", "vendor/*", "assets/node_modules/*"]

remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github

languages: ["es", "en"]
exclude_from_localizations: ["javascript", "images", "css"]

image_sliders:
  - slider1
